const express = require('express');
const router = express.Router();
const paymentController = require('../controllers/payment.controller');
const { authenticateToken, authorizeRole } = require('../middleware/auth');
const multer = require('multer');

// Chek rasmi ma'lumotlar bazasiga (base64) saqlanadi, diskka emas - Render'ning
// bepul tarifidagi disk har deployda tozalanadi va fayllar yo'qolib qolar edi.
const receiptUpload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 4 * 1024 * 1024 },
    fileFilter: (req, file, cb) => {
        if (!file.mimetype.startsWith('image/')) {
            return cb(new Error("Faqat rasm fayllari qabul qilinadi."));
        }
        cb(null, true);
    }
});
const handleReceiptUpload = (req, res, next) => {
    receiptUpload.single('receipt')(req, res, (err) => {
        if (err) {
            return res.status(400).json({ message: err.message || "Chekni yuklashda xatolik yuz berdi." });
        }
        next();
    });
};

// O'quvchilar chek yuklashlari mumkin
router.post('/upload', authenticateToken, authorizeRole('STUDENT'), handleReceiptUpload, paymentController.uploadReceipt);

// Qolganlari faqat adminlar uchun
router.use(authenticateToken, authorizeRole('ADMIN'));

router.get('/students', paymentController.getStudents);
router.get('/', paymentController.getAllPayments);
router.post('/', paymentController.createPayment);
router.post('/auto-debt', paymentController.autoGenerateDebts);
router.post('/sms', paymentController.sendSMS);
router.put('/approve/:id', paymentController.approvePayment);
router.delete('/:id', paymentController.deletePayment);

module.exports = router;
