const express = require('express');
const router = express.Router();
const paymentController = require('../controllers/payment.controller');
const { authenticateToken, authorizeRole } = require('../middleware/auth');
const multer = require('multer');
const path = require('path');

const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        cb(null, 'uploads/');
    },
    filename: (req, file, cb) => {
        cb(null, Date.now() + path.extname(file.originalname));
    }
});
const upload = multer({ storage });

// O'quvchilar chek yuklashlari mumkin
router.post('/upload', authenticateToken, authorizeRole('STUDENT'), upload.single('receipt'), paymentController.uploadReceipt);

// Qolganlari faqat adminlar uchun
router.use(authenticateToken, authorizeRole('ADMIN'));

router.get('/students', paymentController.getStudents);
router.get('/', paymentController.getAllPayments);
router.post('/', paymentController.createPayment);
router.post('/auto-debt', paymentController.autoGenerateDebts);
router.post('/sms', paymentController.sendSMS);
router.put('/approve/:id', paymentController.approvePayment);
router.delete('/:id', paymentController.deletePayment);

module.exports = router;
